[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.5.1", features = [] }
log = "0.4"
tauri-plugin-log = { version = "2.0.2" }

tauri-plugin-sharing = { path = "../../tauri-plugin-sharing" }
tauri-plugin-context-menu = { path = "../../tauri-plugin-context-menu" }
tauri-plugin-map-display = { path = "../../tauri-plugin-map-display" }
tauri-plugin-haptic-feedback = { path = "../../tauri-plugin-haptic-feedback" }
tauri-plugin-geolocation = { path = "../../tauri-plugin-geolocation" }
tauri-plugin-iap = { path = "../../tauri-plugin-iap" }
tauri-plugin-auth = { path = "../../tauri-plugin-auth" }
tauri-plugin-notifications = { path = "../../tauri-plugin-notifications" }
tauri-plugin-ota = { path = "../../tauri-plugin-ota" }
