[package]
name = "tauri-plugin-geolocation"
version = "0.1.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.71"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-geolocation"

[dependencies]
serde = "1.0"
serde_json = "1"
tauri = { version = "2" }
log = "0.4"
thiserror = "1.0"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
