[package]
name = "tauri-plugin-ota"
version = "0.1.0"
authors = [ "You" ]
description = "Tauri Plugin for Over-the-Air updates for iOS applications"
edition = "2021"
rust-version = "1.71"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-ota"

[dependencies]
tauri = { version = "2" }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
reqwest = { version = "0.11", features = ["json"] }
sha2 = "0.10"
hex = "0.4"
tokio = { version = "1", features = ["fs"] }
zip = "0.6"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
